### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException after updating to java SE8 update 51

### ISSUE THREAD

**Issue by drasnop** [desmond-ong/amtBonusScript#1]
I'm using amtBonusScript on a Windows 8.1 laptop, via Cygwin. After updating to the latest JRE (8 update 51), all calls to the Mechanical Turk API would fail with:
`I/O exception (javax.net.ssl.SSLPeerUnverifiedException) caught when processing request: HTTPS hostname invalid: expected '72.21.194.50', received 'mechanicalturk.amazonaws.com'`
making the Command Line Tools basically useless.

After reinstalling the JRE 8 update 45, and changing JAVA_HOME accordingly, everything works again as expected. (You can download old JREs from Oracle's Java Archive: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html. They require you to create a free account for that, which is a pain.)

**Comment by desmond-ong** [comment]
Thank you for this notification! I will add a note to the readme. This looks like a problem with CLT, so it'll be good for people to know.

**Comment by ManjariReddy1** [comment]
Hi,

I am using jboss7.1.0 and apache 2.2.25 and jdk1.7.0.55 version.

when i start export ,facing ----"""" Failed to send the service request, encountered an HTTP I/O er
ror.
HTTPS hostname invalid: expected 'so and so', received 'so and so'"""""

same setup working on morethan 3 env's,htis is new setup for other env.

It would be great ,anyone helps me to solve this solve.

Thanks in advance.

B.R.

Swapna Koppula
